# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest mypy
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Python Code Quality and Lint
        uses: ricardochaves/python-lint@v1.1.0
        with:
          # A list of all paths to test
          python-root-list: . # optional, default is .
          # Use Pylint
          use-pylint: true # optional, default is true
          # Use pycodestyle
          use-pycodestyle: true # optional, default is true
          # Use Flake8
          use-flake8: true # optional, default is true
          # Use Black
          use-black: true # optional, default is true
          # Use mypy
          use-mypy: true # optional, default is true
          # Use isort
          use-isort: true # optional, default is true
      - name: Test with pytest
        run: |
          pytest
